<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<Platforms>x64;ARM64</Platforms>
	<OutputType>WinExe</OutputType>
	<SelfContained>true</SelfContained>
	<RootNamespace>WinRTCOMServer</RootNamespace>
	<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
	<CsWinRTComponent>true</CsWinRTComponent>
	<CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
	<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
	<AssetTargetFallback>net9.0-windows$(TargetPlatformVersion);$(AssetTargetFallback)</AssetTargetFallback>
  </PropertyGroup>
  <PropertyGroup Label="Optimization">
    <TieredPGO>true</TieredPGO>
    <TieredCompilation>true</TieredCompilation>
    <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
    <TieredCompilationQuickJitForLoops>true</TieredCompilationQuickJitForLoops>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Release'">true</PublishReadyToRun>
    <PublishReadyToRunComposite Condition="'$(Configuration)' == 'Release'">true</PublishReadyToRunComposite>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.Ole" Version="4.2.1" />
    <PackageReference Include="Vanara.PInvoke.Shared" Version="4.2.1" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
